### PR TITLE
Only conditionally include <uses-sdk /> in the AndroidManifest.xml wh…

### PR DESCRIPTION
**Pull request by jstedfast**
…en saving

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1874249

### CODE REVIEW

**Review by tondat — APPROVED** [review]

**Review by jonathanpeppers — COMMENTED** [review]
So the design for these should be that:

* `$(TargetPlatformVersion)` is `<uses-sdk android:targetSdkVersion`
* `$(SupportedOSPlatformVersion)` is `<uses-sdk android:minSdkVersion`

`$(SupportedOSPlatformVersion)` is the only one that is possible to be blank, but it's in the project template.

Details here: https://learn.microsoft.com/en-us/dotnet/maui/migration/android-projects?view=net-maui-8.0#changes-to-androidmanifestxml

In what case are you able to make both of these blank?

**Comment by jstedfast** [comment]
@jonathanpeppers net-android projects apparently don't build if AndroidManifest.xml has `<uses-sdk />`

What this patch does is remove the `uses-sdk` XML node if and only if it has no attributes.

Without this change, the `<uses-sdk />` XML element keeps getting added (back) to the AndroidManifest.xml file whenever the user edits that file in the UI editor in VS.

In other words, there's no way for the user to remove it unless they edit it in a text editor and manually remove it.

But if they go back into the UI editor ever in the future to change something, it will get added right back.

This patch fixes that scenario.

**Comment by jonathanpeppers** [comment]
Can we add a unit test in here?

https://github.com/xamarin/xamarin-android-tools/blob/main/tests/Xamarin.Android.Tools.AndroidSdk-Tests/AndroidAppManifestTests.cs

**Comment by jstedfast** [comment]
@jonathanpeppers I just added some tests

**Review by jonathanpeppers — APPROVED** [review]

**Pull request merged**
