### PR TITLE
[Mac] Use the new JdkInfo to fetch the Java SDK path and fix validation

### PR DESCRIPTION
**Pull request by bratsche**
Use JdkInfo to get the Java SDK path, and fix Java SDK validation to work with OpenJDK.

Fixes VSTS #652760 and VSTS #646086

### CODE REVIEW

**Comment by bratsche** [comment]
`ValidateJavaSdkLocation()` used to check the output of `/usr/libexec/java_home`. That won't work with OpenJDK so I'm checking if `$path/bin/javac` exists. Suggestions welcome.

**Comment by jonpryor** [comment]
@bratsche: PR #32 *also* implements the OpenJDK spec; with it, `GetJavaSdkPath()` becomes a one-liner:

```csharp
protected override string GetJavaSdkPath ()
{
    return JdkInfo.GetKnownSystemJdkInfos (Logger).First ();
}
```

**Comment by grendello** [comment]
build

**Comment by jonpryor** [comment]
This PR should be updated to include the one-liner [above](
https://github.com/xamarin/xamarin-android-tools/pull/33#issuecomment-407944339).

**Pull request merged**
